#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


result = 0
sequence = []

#terms < 4000000 # 4 million in fib sequence
val = 1 
val1 = 1
while val <4000000 #terms < 4000000 # 4 million
  sequence << val
  sequence << val1
  val += val1
  val1 += val
end
sequence.shift # Gets rid of first extra number

#find sum of total even valued terms
#puts sequence

idx = 0
while idx < sequence.length
  if sequence[idx] % 2 == 0
    result += sequence[idx]
  end
  
  idx +=1
end

puts result